// This file is kept for backward compatibility.
// Questions are now dynamically generated by Gemini based on the user's resume.
// The static question bank is no longer used.

export const questionBank: never[] = [];

export const categoryLabels: Record<string, string> = {
  react: 'React',
  nextjs: 'Next.js',
  html: 'HTML',
  css: 'CSS',
  javascript: 'JavaScript',
  typescript: 'TypeScript',
  python: 'Python',
  nodejs: 'Node.js',
  sql: 'SQL',
  HR: 'HR',
};

export const categoryColors: Record<string, string> = {
  react: '#61dafb',
  nextjs: '#000000',
  html: '#e34c26',
  css: '#264de4',
  javascript: '#f7df1e',
  typescript: '#3178c6',
  python: '#3776ab',
  HR: '#10b981',
};

// No longer used — kept to avoid import errors in old files
export function getShuffledQuestions(_count: number): never[] {
  return [];
}
